создана система аутентификации и регистрации
gosn1ck/karyeragame pull request #2
Opened 2023-09-23 15:59 UTC by MiheevEvgeniy

2023-09-24 18:14 UTC, SidorovKV requested changes

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/enums/Roles.java
> +}
Нужно добавить роль DEV или SU.

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/dto/NewUserDto.java
> +    @Email(regexp = "^(.+)@(.+)$")
А разве нужна регулярка для этой аннотации?

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/dto/NewUserDto.java
> +    private String password;
Добавить бы поле matchPassword. На фронтэндера надейся, а сам не плошай.

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/dto/UserDto.java
> +    private String password;
Sensetive data. Такое в дто не передают

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/dto/UserDto.java
> +    private Roles role;
Думаю, роли тоже передавать нет необходимости

2023-09-24 18:14 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/model/User.java
> +    private String password;
Подушню и тут немного) 
Не стоит смешивать игровую логику и аунтентификацию в одном месте

2023-09-24 18:14 UTC, SidorovKV commented on src/main/resources/schema.sql
> +        avatar varchar(255) NOT NULL,
Если у нас ограниченное число аватарок, то их лучше вынести в отдельную таблицу и здесь ссылаться на айди записи об аватарке

2023-09-24 18:25 UTC, SidorovKV commented on erd.png
Нужна ещё одна таблица account_type и ссылка на нее из accounts.
Таблица будет содержать типы акков (личный, председатель, полиция и т.д.)

2023-09-25 17:09 UTC, gosn1ck reviewed
Хорошая работа, молодец!
Я б рекомендовал ручку по регистрации вынести в /auth, а все остальные методы - доступны только авторизованным пользователям и возможно с некоторой ролью. можем обсудить голосом на демо

2023-09-25 17:09 UTC, gosn1ck commented on src/main/java/ru/karyeragame/paymentsystem/user/service/UserServiceImpl.java
> +        return mapper.toDto(repository.save(user));
с БД работаем, @Transactional не нужно?

2023-09-25 17:09 UTC, gosn1ck commented on src/main/java/ru/karyeragame/paymentsystem/user/service/UserServiceImpl.java
> +        throw new NotFoundException("User not found");
выше писал, можно в 1 строку
```
return repo.findById(id)
                .orElseThrow(() -> new NotFoundException("userwith id %d not found", id))
```

2023-09-25 17:09 UTC, gosn1ck commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
мы h2 для будущих тестовом завозим?

2023-09-25 17:32 UTC, gosn1ck commented on src/main/java/ru/karyeragame/paymentsystem/user/service/UserServiceImpl.java
> +        PagedListHolder<UserDto> page = new PagedListHolder<>(repository.findAll()
кажется тут не оптимально сделано, вытаскиваются из БД кажется все объекты. почем б Page<T> findAll(Pageable pageable); не воспользоваться?

2023-09-25 17:39 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/enums/Roles.java
> +}
> что это за роли? пока этих 2х думаю достаточно

Из новой версии ТЗ. Там прописан "Аккаунт Разработчика", который назначает администратора игры в начале новой игры

2023-09-25 17:41 UTC, MiheevEvgeniy commented on src/main/java/ru/karyeragame/paymentsystem/exceptions/ErrorHandler.java
> +    public ErrorResponse handleNotFoundException(final Exception e) {
так можно сделать пока метод один. Я сделал такое имя на будущее.

2023-09-25 17:43 UTC, MiheevEvgeniy commented on src/main/java/ru/karyeragame/paymentsystem/exceptions/ErrorHandler.java
> +        public String toString() {
Слышал, что best practice переопределять equals, hashcode и tostring вручную. В принципе для tostring можно сделать исключение, но мне показалось, что так оптимальнее. Если нужно - исправлю

2023-09-25 17:45 UTC, MiheevEvgeniy commented on src/main/java/ru/karyeragame/paymentsystem/security/CustomUserDetailsService.java
> +    @Autowired
Что именно? Autowired? Лучше использовать RequiredArgsConstructor?

2023-09-25 17:47 UTC, MiheevEvgeniy commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
я для своих тестов подключаю обычно. Оставил для других участников на всякий случай. В продакшн он, конечно, не пойдет))

2023-09-25 17:50 UTC, MiheevEvgeniy commented on erd.png
да, это уже про аккаунты)

2023-09-25 17:52 UTC, MiheevEvgeniy commented on src/main/java/ru/karyeragame/paymentsystem/user/model/User.java
> +    private String password;
в моем представлении она не смешивается, т.к. игровая логика будет в аккаунтах пользователей, а я сделал скорее сущность пользователя с его личными данными.

2023-09-25 18:00 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/user/model/User.java
> +    private String password;
Такая сильная связность может в будущем усложнить разделение ответственностей. Не в этом проекте, так в другом. Плохие привычки быстро въедаются в подкорку)) Ведь так проще делать на краткосрочной дистанции

2023-09-25 19:10 UTC, MiheevEvgeniy commented on src/main/java/ru/karyeragame/paymentsystem/security/SecurityConfig.java
> +                .httpBasic(Customizer.withDefaults())
в постмане тогда не получается авторизироваться через basicAuth

2023-09-25 19:18 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/security/SecurityConfig.java
> +                .httpBasic(Customizer.withDefaults())
> в постмане тогда не получается авторизироваться через basicAuth

Тогда получается, formLogin лишняя, если basic auth'ом авторизация всегда осуществляется. Basic auth в хэдерах логин пароль будет всегда слать, и фронту их нужно будет хранить получается, чтобы на каждый защищённый эндпоинт доступ получить. Выдачу-проверку токенов я не увидел

2023-09-26 14:27 UTC, Rohma999 commented on src/main/java/ru/karyeragame/paymentsystem/enums/Roles.java
> +public enum Roles {
Можно сделать так:
public enum Roles implements GrantedAuthority

2023-09-26 14:32 UTC, Rohma999 commented on src/main/java/ru/karyeragame/paymentsystem/security/UserDetailsImpl.java
> +        this.authorities = List.of(user.getRole().name())
Если сделаешь как я написал про enum,то тут можно будет сделать так :
this.authorities = Collections.singleton(user.getRole())
Collections.singleton конечно если подразумевается что у пользователя одна роль

2023-09-27 07:42 UTC, gringrowin approved these changes

2023-09-27 12:48 UTC, gosn1ck approved these changes

2023-09-27 12:50 UTC, merged