Add EmailSender
gosn1ck/karyeragame pull request #3
Opened 2023-09-24 11:26 UTC by AndMolPraktikum

2023-09-27 07:30 UTC, SidorovKV requested changes

2023-09-27 07:30 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +public record EmailServiceImpl(JavaMailSender javaMailSender) implements EmailService {
А почему сервис сделан через record, а EmailMessage через class?

2023-09-27 07:30 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +        message.setFrom("careerA.game@gmail.com");
Может лучше почтовый адрес тоже вынести в пропертис?

2023-09-27 07:30 UTC, SidorovKV commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +        helper.setFrom("careerA.game@gmail.com");
И тут

2023-09-27 13:26 UTC, Andrey-VU commented
Андрей, давай всё это завернём в package mailSender

2023-09-28 16:01 UTC, AndMolPraktikum commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +public record EmailServiceImpl(JavaMailSender javaMailSender) implements EmailService {
Я EmailMessage делал для тестов, он будет удален, я полагаю. Но поправил.

2023-09-28 16:09 UTC, AndMolPraktikum commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +        message.setFrom("careerA.game@gmail.com");
Вынес

2023-09-28 16:09 UTC, AndMolPraktikum commented on src/main/java/ru/karyeragame/paymentsystem/service/EmailServiceImpl.java
> +        helper.setFrom("careerA.game@gmail.com");
Вынес

2023-09-29 08:58 UTC, Andrey-VU approved these changes

2023-09-29 12:13 UTC, gosn1ck approved these changes

2023-09-29 12:13 UTC, merged